title: "Chris McComb, Ph.D."
description: "Research, publications, and professional profile for Chris McComb."
url: "https://cmccomb.com"
timezone: "America/New_York"
author: "Chris McComb, Ph.D."
affiliation: "<a href='https://meche.engineering.cmu.edu/directory/bios/mccomb-christopher.html'>Professor @ CMU</a>"
email: ccm@cmu.edu
twitter: ccmccomb
github: cmccomb
linkedin: ccmcc
google_scholar: 0P9w_S0AAAAJ
headshot: 'assets/images/headshot_optimized_square.jpg'
