# Permalinks
permalink:        pretty

# Setup
title:		  Chris McComb
raised:     Chris M<span style="vertical-align:18%">c</span>Comb
tagline:          ''
description1:   Assistant Professor
description2:   <a href="http://sedtapp.psu.edu">SEDTAPP</a> @ <a href="http://www.psu.edu">PSU</a>
url:              http://www.cmccomb.com
baseurl:          /
repository: cmccomb/cmccomb.github.io-source

author:
  name:           'Chris McComb'
  url:            http://www.cmccomb.com

plugins:
    - classifier-reborn
    - jekyll-github-metadata

lsi: false

permalink: /publications/:year/:title/

collections:
  news:
    output: true
    permalink: /news/:year/:month/:day/:title/
