title: "Chris McComb, Ph.D."
author: "Chris McComb, Ph.D."
affiliation: "<a href='https://meche.engineering.cmu.edu/directory/bios/mccomb-christopher.html'>Associate Professor @ CMU</a>"
email: ccm@cmu.edu
twitter: ccmccomb
github: cmccomb
google_scholar: 0P9w_S0AAAAJ
headshot: 'assets/images/headshot_optimized_square.jpg'
