# Permalinks
permalink:        pretty

# Setup
title:		  Chris McComb
raised:     Chris M<span style="vertical-align:18%">c</span>Comb
tagline:          ''
description1:   Assistant Professor
description2:   <a href="">SEDTAPP</a> @ <a href="">PSU</a>
url:              http://www.cmccomb.com
baseurl:          /

author:
  name:           'Chris McComb'
  url:            http://www.cmccomb.com

gems: [classifier-reborn]
lsi: false

permalink: /publications/:year/:title/

collections:
  news:
    output: true
    permalink: /news/:year/:month/:day/:title/
