# Permalinks
permalink:        pretty

# Setup
title:		  Chris McComb
raised:     Chris M<span style="vertical-align:18%">c</span>Comb
tagline:          ''
description1:   Assistant Professor
description2:   <a href="http://sedtapp.psu.edu">SEDTAPP</a> @ <a href="http://www.psu.edu">PSU</a>
url:              https://www.cmccomb.com
baseurl:          https://www.cmccomb.com/
repository: cmccomb/cmccomb.github.io-source

author:
  name:           'Chris McComb'
  url:            https://www.cmccomb.com

# plugins:
    # - classifier-reborn
#    - jekyll-github-metadata

lsi: false

permalink: /publications/:year/:title/

collections:
  cv:
    output: false

office: 213U Hammond Building
address: University Park, PA 16802
email: "mccomb@psu.edu"
website: "thred.psu.edu"

theme: jekyll-theme-cayman
