name: Monthly publication refresh

on:
  schedule:
    - cron: '0 6 1 * *'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install publication tooling
        run: pip install -r _scripts/requirements.txt
      - name: Build full publication dataset
        run: python _scripts/build_json.py --force
      - name: Upload publication payload
        uses: actions/upload-artifact@v4
        with:
          name: publication-payload-monthly
          path: assets/json/pubs.json
          if-no-files-found: error
