name: Test serve script

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Bats
        run: sudo apt-get update && sudo apt-get install -y bats
      - name: Run tests
        run: bats tests/serve.bats
